### ISSUE TITLE
Locking down dependency tree for Noddity

### ISSUE THREAD

**Issue by saibotsivad** [TehShrike/noddity#44]
It's come up in discussion more than once that some site may be having a problem because we are unsure if a dependency somewhere up the tree is actually being used.

E.g. [an update of noddity-render-dom](https://github.com/ArtskydJ/noddity-render-dom/pull/20/commits) appears to have fixed #41 but how would a user know whether running `noddity-installer` produced a built output that used that version?

If there's another way that'd be cool, but I think it might be appropriate to use [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) on published versions of noddity, so that the built output is 100% reproducible.

**Comment by TehShrike** [comment]
There's two issues here - the first is that we're not bumping dependencies aggressively enough.  That uncertainty does suck.

I should set up [greenkeeper](https://greenkeeper.io/) for all the Noddity repositories.

Shrinkwrapping is a good paranoid step, but personally if I'm depending on a specific version of e.g. noddity-butler, and a patch is published to levelup-cache, I'm fine with getting that patch the next time I install noddity-butler.  This is because I maintain both libraries myself and I trust myself to use semver appropriately, and it's certainly arguable whether it should remain the policy going forwards.

In any case, I think the two could be discussed as separate issues, and hopefully greenkeeper will solve the first issue.

**Comment by saibotsivad** [comment]
Yeah, seems like Greenkeeper would be the ideal solution. 👍

**Comment by TehShrike** [comment]
With Greenkeeper, we should at least have open issues for all dependencies that need updated.
